### ISSUE TITLE
replace a tag to a `Link` tag from `next/link`.

### ISSUE THREAD

**Issue by Lada496** [van-squad/map-t3#32]
I think we can replace a tag to a `Link` tag from `next/link`.

[Next.js / Link](https://nextjs.org/docs/app/api-reference/components/link)

_Originally posted by @keento0809 in https://github.com/van-squad/map-t3/pull/17#discussion_r1246087776_

**Comment by SachiGoto** [comment]
I remember changing a tag to Link tag and changed px to rem the other day. But just noticed that I didn't push the code lol 
I'm push the code once all the file & folder structure are re-organized.

**Comment by Lada496** [comment]
https://github.com/van-squad/map-t3/blob/ff6a43ec80bb0986fe08a76b621e4a06b119af16/src/clients/components/FavCards.tsx#L109-L117
Also, if you could include the updates to replace from <img> to [Image](https://nextjs.org/docs/pages/api-reference/components/image), that would be great.

**Comment by Lada496** [comment]
#36
