### ISSUE TITLE
Update the button stylings for Card component

### ISSUE THREAD

**Issue by Lada496** [van-squad/map-t3#84]
I should've mentioned it beforehand but it might be better to update the "View Details" button in terms of accessibility optimization. For example, changing the background color from transparent to white or even just adding a see-through white background helps users to recognize the button.

_Originally posted by @Lada496 in https://github.com/van-squad/map-t3/issues/81#issuecomment-1765634131_

**Comment by Lada496** [comment]
<img width="750" alt="Screenshot 2023-10-16 at 21 11 44" src="https://github.com/van-squad/map-t3/assets/67321065/729ce5e9-85c8-4475-841f-25fd61387980">

**Comment by Lada496** [comment]
FYI:
Generally, text and image-text have to have 4.5: 1 contrast. If texts are large enough, the contrast can be 3:1.
- about minimum contrast: https://www.w3.org/TR/WCAG21/#contrast-minimum
- about large text: https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#larger-scaledef
- https://webaim.org/resources/contrastchecker/

These matters are more within the domain of designers, imo tho...

**Comment by SachiGoto** [comment]
@Lada496, you make a great point! We need to prioritize web accessibility. Maybe we can allocate some time to work on web accessibility for the entire website once we have the functionality in place.
